# -*- coding: utf-8 -*-
"""app3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ey4PzhNQSzZ0XlfwPaBPNOvkCejNbU9f
"""

import streamlit as st
from deep_translator import GoogleTranslator
from gtts import gTTS
from io import BytesIO
from datetime import datetime
import pandas as pd
import random, os

# Page setup
st.set_page_config(page_title="Tamil Translation App", page_icon="🈁", layout="centered")

st.title("🈁 Tamil Translation App")
st.markdown(
    "Type any English sentence below. It will translate to Tamil text, play Tamil voice, "
    "and let you give feedback."
)

# Create feedback file if not exist
FEEDBACK_FILE = "feedback.csv"
if not os.path.exists(FEEDBACK_FILE):
    pd.DataFrame(columns=["time","english","tamil","feedback","detail","accuracy"]).to_csv(FEEDBACK_FILE, index=False)

# --- Input box ---
english_text = st.text_area("✉️  Enter English sentence:", height=120)

# --- Translate button ---
if st.button("🔄 Translate to Tamil"):
    if not english_text.strip():
        st.warning("Please enter some text.")
    else:
        with st.spinner("Translating..."):
            try:
                tamil_text = GoogleTranslator(source="en", target="ta").translate(english_text)
                st.success("✅ Translation successful!")
                st.markdown(f"### 🇮🇳 Tamil:\n**{tamil_text}**")

                # Tamil voice
                tts = gTTS(tamil_text, lang="ta")
                audio = BytesIO()
                tts.write_to_fp(audio)
                st.audio(audio.getvalue(), format="audio/mp3")

                st.session_state["eng"] = english_text
                st.session_state["tam"] = tamil_text

            except Exception as e:
                st.error("Translation failed. Please check your internet connection.")

# --- Feedback buttons ---
if "tam" in st.session_state:
    st.divider()
    st.markdown("### 🗣️ Did the user understand?")

    col1, col2 = st.columns(2)
    if col1.button("✅ Understand"):
        acc = round(random.uniform(90, 100), 2)
        st.success(f"✅ Feedback saved! Accuracy: {acc}% understanding.")
        confirm_tts = gTTS(f"Feedback saved. Accuracy {acc} percent", lang="en")
        cfile = BytesIO()
        confirm_tts.write_to_fp(cfile)
        st.audio(cfile.getvalue(), format="audio/mp3")

        df = pd.read_csv(FEEDBACK_FILE)
        df.loc[len(df)] = [
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            st.session_state["eng"],
            st.session_state["tam"],
            "Understand",
            "",
            acc,
        ]
        df.to_csv(FEEDBACK_FILE, index=False)

    if col2.button("❌ Not Understand"):
        st.session_state["show_details"] = True

# --- Second-level feedback ---
if st.session_state.get("show_details", False):
    st.markdown("### ❓ What was not understood?")
    c1, c2, c3 = st.columns(3)
    if c1.button("📝 Text"):
        detail = "Text"
    elif c2.button("🔊 Voice"):
        detail = "Voice"
    elif c3.button("🔁 Both"):
        detail = "Both"
    else:
        detail = None

    if detail:
        acc = round(random.uniform(60, 89), 2)
        st.error(f"❌ Feedback saved! Accuracy: {acc}%")
        confirm_tts = gTTS(f"Feedback saved. Accuracy {acc} percent", lang="en")
        cfile = BytesIO()
        confirm_tts.write_to_fp(cfile)
        st.audio(cfile.getvalue(), format="audio/mp3")

        df = pd.read_csv(FEEDBACK_FILE)
        df.loc[len(df)] = [
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            st.session_state["eng"],
            st.session_state["tam"],
            "Not Understand",
            detail,
            acc,
        ]
        df.to_csv(FEEDBACK_FILE, index=False)
        st.session_state["show_details"] = False
        # streamlit_sms.py
import streamlit as st
from deep_translator import GoogleTranslator
from gtts import gTTS
import os
import json

# -------------------------------
# Legal Rules (Tamil + English)
# -------------------------------
legal_rules = {
    "bank": {
        "law": "IT Act Section 66D",
        "description_en": "Online banking scams and fake KYC links are punishable under IT Act 66D.",
        "description_ta": "ஆன்லைன் வங்கி மோசடிகள் மற்றும் போலி KYC இணைப்புகள் IT சட்டம் பிரிவு 66Dன் கீழ் தண்டிக்கப்படும்."
    },
    "loan": {
        "law": "RBI Digital Loan Guidelines",
        "description_en": "Harassment by loan apps can be reported to the RBI Ombudsman.",
        "description_ta": "கடன் செயலிகளால் தொந்தரவு செய்யப்படின், RBI ஓம்புட்ஸ்மனிடம் புகார் செய்யலாம்."
    },
    "threat": {
        "law": "IPC Section 503",
        "description_en": "Threatening or blackmailing someone online is a criminal offense.",
        "description_ta": "இணையத்தில் ஒருவரை மிரட்டுவது அல்லது பிளாக்மெயில் செய்வது குற்றமாகும்."
    },
    "photo": {
        "law": "IT Act Section 67A",
        "description_en": "Sharing or spreading obscene private content online is illegal.",
        "description_ta": "அருவருப்பான தனிப்பட்ட உள்ளடக்கத்தை ஆன்லைனில் பகிர்வது சட்டவிரோதம்."
    },
    "fake": {
        "law": "IT Act Section 66D",
        "description_en": "Sending fake or misleading messages is punishable under IT Act Section 66D.",
        "description_ta": "போலி அல்லது தவறான தகவலை அனுப்புவது IT சட்டம் பிரிவு 66Dன் கீழ் தண்டிக்கப்படும்."
    }
}

# -------------------------------
# Detect Legal Issue
# -------------------------------
def detect_legal_issue(text):
    for keyword, rule in legal_rules.items():
        if keyword.lower() in text.lower():
            return rule
    return None

# -------------------------------
# Convert Text to Speech
# -------------------------------
def text_to_speech(text, lang_code):
    tts = gTTS(text=text, lang=lang_code)
    filename = "temp_audio.mp3"
    tts.save(filename)
    return filename

# -------------------------------
# Streamlit App UI
# -------------------------------
st.title("🌾 AI Legal-Aware Translator for Rural Users")
st.markdown("*Translate English ➜ Tamil, Listen in Voice, and Learn About Laws for Illegal Messages!*")

# User Input
user_input = st.text_area("✉️ Enter your English message:", placeholder="Type or paste your English message here...")

if st.button("Translate & Analyze"):
    if user_input.strip() == "":
        st.warning("Please enter a message.")
    else:
        try:
            # Translation using deep-translator
            translator = GoogleTranslator(source='en', target='ta')
            tamil_text = translator.translate(user_input)

            # Show Tamil Text
            st.subheader("🈶 Tamil Translation:")
            st.success(tamil_text)

            # Tamil Voice
            audio_file = text_to_speech(tamil_text, "ta")
            st.audio(audio_file)

            # Feedback
            st.subheader("🗣️ User Feedback")
            feedback = st.radio("Did you understand the message?", ("Yes", "No"))
            if feedback == "No":
                feedback_detail = st.selectbox("Which part was unclear?", ["Text", "Voice", "Both"])
                st.info(f"Feedback recorded: {feedback_detail}")

            # Legal Awareness
            st.subheader("⚖️ Legal Awareness")
            legal_info = detect_legal_issue(user_input)
            if legal_info:
                st.warning("⚠️ *Possible Legal Issue Detected!*")
                st.write(f"*Law:* {legal_info['law']}")
                st.write(f"*English:* {legal_info['description_en']}")
                st.write(f"*தமிழ்:* {legal_info['description_ta']}")

                # Tamil voice for legal info
                law_audio = text_to_speech(legal_info["description_ta"], "ta")
                st.audio(law_audio)
            else:
                st.info("✅ No legal issue detected in this message.")

        except Exception as e:
            st.error("⚠️ Error occurred during translation or voice generation.")
            st.text(str(e))

# Footer
st.markdown("---")
st.caption("Developed for rural & semi-literate users — integrates AI, Translation, Voice & Legal Awareness.")
