# -*- coding: utf-8 -*-
"""app3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ey4PzhNQSzZ0XlfwPaBPNOvkCejNbU9f
"""

import streamlit as st
from deep_translator import GoogleTranslator
from gtts import gTTS
from io import BytesIO
from datetime import datetime
import pandas as pd
import random, os

# Page setup
st.set_page_config(page_title="Tamil Translation App", page_icon="🈁", layout="centered")

st.title("🈁 Tamil Translation App")
st.markdown(
    "Type any English sentence below. It will translate to Tamil text, play Tamil voice, "
    "and let you give feedback."
)

# Create feedback file if not exist
FEEDBACK_FILE = "feedback.csv"
if not os.path.exists(FEEDBACK_FILE):
    pd.DataFrame(columns=["time","english","tamil","feedback","detail","accuracy"]).to_csv(FEEDBACK_FILE, index=False)

# --- Input box ---
english_text = st.text_area("✉️  Enter English sentence:", height=120)

# --- Translate button ---
if st.button("🔄 Translate to Tamil"):
    if not english_text.strip():
        st.warning("Please enter some text.")
    else:
        with st.spinner("Translating..."):
            try:
                tamil_text = GoogleTranslator(source="en", target="ta").translate(english_text)
                st.success("✅ Translation successful!")
                st.markdown(f"### 🇮🇳 Tamil:\n**{tamil_text}**")

                # Tamil voice
                tts = gTTS(tamil_text, lang="ta")
                audio = BytesIO()
                tts.write_to_fp(audio)
                st.audio(audio.getvalue(), format="audio/mp3")

                st.session_state["eng"] = english_text
                st.session_state["tam"] = tamil_text

            except Exception as e:
                st.error("Translation failed. Please check your internet connection.")

# --- Feedback buttons ---
if "tam" in st.session_state:
    st.divider()
    st.markdown("### 🗣️ Did the user understand?")

    col1, col2 = st.columns(2)
    if col1.button("✅ Understand"):
        acc = round(random.uniform(90, 100), 2)
        st.success(f"✅ Feedback saved! Accuracy: {acc}% understanding.")
        confirm_tts = gTTS(f"Feedback saved. Accuracy {acc} percent", lang="en")
        cfile = BytesIO()
        confirm_tts.write_to_fp(cfile)
        st.audio(cfile.getvalue(), format="audio/mp3")

        df = pd.read_csv(FEEDBACK_FILE)
        df.loc[len(df)] = [
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            st.session_state["eng"],
            st.session_state["tam"],
            "Understand",
            "",
            acc,
        ]
        df.to_csv(FEEDBACK_FILE, index=False)

    if col2.button("❌ Not Understand"):
        st.session_state["show_details"] = True

# --- Second-level feedback ---
if st.session_state.get("show_details", False):
    st.markdown("### ❓ What was not understood?")
    c1, c2, c3 = st.columns(3)
    if c1.button("📝 Text"):
        detail = "Text"
    elif c2.button("🔊 Voice"):
        detail = "Voice"
    elif c3.button("🔁 Both"):
        detail = "Both"
    else:
        detail = None

    if detail:
        acc = round(random.uniform(60, 89), 2)
        st.error(f"❌ Feedback saved! Accuracy: {acc}%")
        confirm_tts = gTTS(f"Feedback saved. Accuracy {acc} percent", lang="en")
        cfile = BytesIO()
        confirm_tts.write_to_fp(cfile)
        st.audio(cfile.getvalue(), format="audio/mp3")

        df = pd.read_csv(FEEDBACK_FILE)
        df.loc[len(df)] = [
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            st.session_state["eng"],
            st.session_state["tam"],
            "Not Understand",
            detail,
            acc,
        ]
        df.to_csv(FEEDBACK_FILE, index=False)
        st.session_state["show_details"] = False
        # streamlit_sms.py
import streamlit as st
from deep_translator import GoogleTranslator
from gtts import gTTS
import os

# ---------------------------
# ⚖️ Scam detection keywords
# ---------------------------
SCAM_KEYWORDS = [
    "otp", "reward", "lottery", "bank", "money", "click link",
    "account", "loan", "prize", "gift", "password", "update", "offer"
]

def check_scam_message(message):
    for word in SCAM_KEYWORDS:
        if word.lower() in message.lower():
            return True
    return False

# ---------------------------
# 🧠 Tamil meaning dictionary
# ---------------------------
TAMIL_DICTIONARY = {
    "fraudulent": "மோசடி செய்வது",
    "beware": "எச்சரிக்கையாக இரு",
    "scam": "மோசடி",
    "loan": "கடன்",
    "reward": "பரிசு",
    "bank": "வங்கி",
    "account": "கணக்கு",
    "password": "கடவுச்சொல்",
    "fake": "போலி",
    "offer": "சலுகை"
}

def explain_difficult_words(msg):
    explanations = []
    words = msg.lower().split()
    for word in words:
        if word in TAMIL_DICTIONARY:
            explanations.append(f"'{word}' means '{TAMIL_DICTIONARY[word]}' in Tamil.")
    return explanations

# ---------------------------
# 🌾 Streamlit UI
# ---------------------------
st.set_page_config(page_title="AI Legal-Aware Translator", page_icon="⚖️")
st.title("⚖️ AI Legal-Aware English–Tamil Translator for Rural Users")
st.write("This app helps rural users translate English messages into Tamil with voice support, scam detection (IT Act 66D), and simple Tamil word explanations.")

msg = st.text_area("✍️ Enter English message or paragraph:")

if st.button("Translate"):
    if msg.strip() == "":
        st.warning("Please enter some English text.")
    else:
        try:
            # Translate English → Tamil
            tamil_text = GoogleTranslator(source='en', target='ta').translate(msg)

            st.write("### 🈶 Tamil Translation:")
            st.success(tamil_text)

            # Text-to-speech output
            tts = gTTS(tamil_text, lang='ta')
            tts.save("output.mp3")
            st.audio("output.mp3")

            # Scam message warning
            if check_scam_message(msg):
                st.error("⚠️ இந்த செய்தி மோசடி (Scam) செய்தியாக இருக்கலாம்! IT Act 66D சட்டத்தின் கீழ் நடவடிக்கை எடுக்கலாம்.")
                st.info("🛡️ Legal Section: Your Rights — Fake SMS Law (IT Act Section 66D).")

            # Smart meaning assistant
            explanations = explain_difficult_words(msg)
            if explanations:
                st.info("### 🧠 Smart Meaning Assistant:")
                for exp in explanations:
                    st.write(exp)

                # Optional Tamil voice for meanings
                meaning_text = " ".join([TAMIL_DICTIONARY.get(w.strip("'"), "") for w in msg.lower().split() if w in TAMIL_DICTIONARY])
                if meaning_text:
                    tts2 = gTTS(meaning_text, lang='ta')
                    tts2.save("meaning.mp3")
                    st.audio("meaning.mp3")

        except Exception as e:
            st.error("An error occurred while translating or generating voice. Please try again.")
            st.write("Error details:", e)

st.markdown("---")
st.caption("🧩 Developed for rural and semi-literate users – combines AI translation, Tamil voice, and legal awareness.")
