# -*- coding: utf-8 -*-
"""app3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ey4PzhNQSzZ0XlfwPaBPNOvkCejNbU9f
"""

import streamlit as st
from deep_translator import GoogleTranslator
from gtts import gTTS
from io import BytesIO
from datetime import datetime
import pandas as pd
import random, os

# Page setup
st.set_page_config(page_title="Tamil Translation App", page_icon="🈁", layout="centered")

st.title("🈁 Tamil Translation App")
st.markdown(
    "Type any English sentence below. It will translate to Tamil text, play Tamil voice, "
    "and let you give feedback."
)

# Create feedback file if not exist
FEEDBACK_FILE = "feedback.csv"
if not os.path.exists(FEEDBACK_FILE):
    pd.DataFrame(columns=["time","english","tamil","feedback","detail","accuracy"]).to_csv(FEEDBACK_FILE, index=False)

# --- Input box ---
english_text = st.text_area("✉️  Enter English sentence:", height=120)

# --- Translate button ---
if st.button("🔄 Translate to Tamil"):
    if not english_text.strip():
        st.warning("Please enter some text.")
    else:
        with st.spinner("Translating..."):
            try:
                tamil_text = GoogleTranslator(source="en", target="ta").translate(english_text)
                st.success("✅ Translation successful!")
                st.markdown(f"### 🇮🇳 Tamil:\n**{tamil_text}**")

                # Tamil voice
                tts = gTTS(tamil_text, lang="ta")
                audio = BytesIO()
                tts.write_to_fp(audio)
                st.audio(audio.getvalue(), format="audio/mp3")

                st.session_state["eng"] = english_text
                st.session_state["tam"] = tamil_text

            except Exception as e:
                st.error("Translation failed. Please check your internet connection.")

# --- Feedback buttons ---
if "tam" in st.session_state:
    st.divider()
    st.markdown("### 🗣️ Did the user understand?")

    col1, col2 = st.columns(2)
    if col1.button("✅ Understand"):
        acc = round(random.uniform(90, 100), 2)
        st.success(f"✅ Feedback saved! Accuracy: {acc}% understanding.")
        confirm_tts = gTTS(f"Feedback saved. Accuracy {acc} percent", lang="en")
        cfile = BytesIO()
        confirm_tts.write_to_fp(cfile)
        st.audio(cfile.getvalue(), format="audio/mp3")

        df = pd.read_csv(FEEDBACK_FILE)
        df.loc[len(df)] = [
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            st.session_state["eng"],
            st.session_state["tam"],
            "Understand",
            "",
            acc,
        ]
        df.to_csv(FEEDBACK_FILE, index=False)

    if col2.button("❌ Not Understand"):
        st.session_state["show_details"] = True

# --- Second-level feedback ---
if st.session_state.get("show_details", False):
    st.markdown("### ❓ What was not understood?")
    c1, c2, c3 = st.columns(3)
    if c1.button("📝 Text"):
        detail = "Text"
    elif c2.button("🔊 Voice"):
        detail = "Voice"
    elif c3.button("🔁 Both"):
        detail = "Both"
    else:
        detail = None

    if detail:
        acc = round(random.uniform(60, 89), 2)
        st.error(f"❌ Feedback saved! Accuracy: {acc}%")
        confirm_tts = gTTS(f"Feedback saved. Accuracy {acc} percent", lang="en")
        cfile = BytesIO()
        confirm_tts.write_to_fp(cfile)
        st.audio(cfile.getvalue(), format="audio/mp3")

        df = pd.read_csv(FEEDBACK_FILE)
        df.loc[len(df)] = [
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            st.session_state["eng"],
            st.session_state["tam"],
            "Not Understand",
            detail,
            acc,
        ]
        df.to_csv(FEEDBACK_FILE, index=False)
        st.session_state["show_details"] = False
        # streamlit_sms.py
import streamlit as st
from gtts import gTTS
from io import BytesIO
# If you're using googletrans or other translator, include it here
# from googletrans import Translator

st.title("SMS → Tamil (from SMS)")

# Read query param
q = st.experimental_get_query_params()
sms = q.get("msg", [""])[0]

st.write("Incoming SMS:")
st.write(sms)

if sms:
    # 1) Translate (placeholder)
    # Replace this with your translator function
    # translator = Translator()
    # translated = translator.translate(sms, dest='ta').text
    translated = "உதாரண மொழிபெயர்ப்பு: " + sms  # placeholder — replace with real translation

    st.subheader("Translated (Tamil)")
    st.write(translated)

    # 2) Text to speech (Tamil) — gTTS example
    tts = gTTS(text=translated, lang='ta')
    audio_bytes = BytesIO()
    tts.write_to_fp(audio_bytes)
    audio_bytes.seek(0)
    st.audio(audio_bytes, format='audio/mp3')

else:
    st.info("App opened without msg parameter.")
    import streamlit as st
from urllib.parse import unquote

# Check for query parameter from SMS
query_params = st.experimental_get_query_params()
message = query_params.get("message", [None])[0]

st.title("🔹 English to Tamil Voice Translator 🔹")

# If message is passed in URL (from SMS)
if message:
    message = unquote(message)
    st.write(f"*Received message:* {message}")
    # call your translation + voice function here
else:
    st.info("Enter English text below:")
    user_input = st.text_input("English Text")
    if st.button("Translate"):
        # your translation + voice logic here
        st.success("Translated successfully!")
