# -*- coding: utf-8 -*-
"""app4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ey4PzhNQSzZ0XlfwPaBPNOvkCejNbU9f
"""

import streamlit as st
from deep_translator import GoogleTranslator
from gtts import gTTS
import tempfile
import os

# --- Page setup ---
st.set_page_config(page_title="SMS Tamil Translator", page_icon="📩", layout="centered")
st.title("📩 Incoming SMS → Tamil Translation + Voice")

# --- 1. Get text from URL or input ---
query_params = st.query_params
text = query_params.get("text", [""])[0] if "text" in query_params else ""

if not text:
    text = st.text_area("Paste your message text here 👇", "")

if st.button("Translate to Tamil") or text:
    if text.strip() != "":
        # --- 2. Translate English → Tamil ---
        translator = Translator()
        result = translator.translate(text, src="auto", dest="ta").text

        st.subheader("🔤 Translated Tamil Text:")
        st.success(result)

        # --- 3. Speak Tamil (Text-to-Speech) ---
        tts = gTTS(result, lang="ta")
        with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as fp:
            tts.save(fp.name)
            st.audio(fp.name, format="audio/mp3")

        # --- 4. Feedback Section ---
        st.write("🗣️ Give Feedback on Translation:")
        col1, col2 = st.columns(2)
        with col1:
            if st.button("👍 Good"):
                st.session_state["feedback"] = "Good"
        with col2:
            if st.button("👎 Bad"):
                st.session_state["feedback"] = "Bad"

        if "feedback" in st.session_state:
            st.info(f"✅ Your feedback: {st.session_state['feedback']}")
            # (optional: save feedback in a file or database)

    else:
        st.warning("Please enter or receive some text.")
